#! /bin/sh

rm *.o
gmake clean
cp -f config.ib_intel config
gmake NCPUS=64 -j 4
mv -f tacc_stats tacc_stats.ib_intel

rm *.o
gmake clean
cp -f config.ib_amd config
gmake NCPUS=32 -j 4
mv -f tacc_stats tacc_stats.ib_amd
rm -f config
