#!/bin/bash

prog="$(basename $0)"
accounting_file=/share/sge6.2/default/common/accounting

trace() {
    if [ -n "$DEBUG" ]; then
        echo "$1" >&2
    fi
}

fatal() {
    echo "$1" >&2
    exit 1
}

jobid=$1
if [ -z "$jobid" ]; then
    fatal "$prog: must specify a jobid"
fi

# Some interesting accounting file fields.
# $1 queue
# $4 owner
# $5 job_name
# $6 jobid
# $10 start_time
# $11 end_time
# $34 granted_pe
# $35 slots

awk -F : '
$6 == jobid {
  print $10, $11;
  exit 0;
}
END {
  exit 1;
}' jobid="$jobid" $accounting_file
