#!/bin/bash

prog="$(basename $0)"
accounting_file=/share/sge6.2/default/common/accounting
hostfile_dir=/share/sge6.2/default/tacc/hostfile_logs

trace() {
    if [ -n "$DEBUG" ]; then
        echo "$1" >&2
    fi
}

fatal() {
    echo "$1" >&2
    exit 1
}

job_id=$1
if [ -z "$job_id" ]; then
    fatal "$prog: must specify a job ID"
fi

job_record="$(awk -F: -v job_id=$job_id '$6 == job_id' $accounting_file)"
if [ -z "$job_record" ]; then
     fatal "$prog: cannot find accounting data for job $job_id"
fi

OLD_IFS=$IFS
IFS=:
job_info=( ${job_record} )
IFS=$OLD_IFS

job_begin=${job_info[9]}

get_host_file() {
    id=$1
    begin=$2
    for delta in 0 -3600 3600; do
        epoch=$((begin + delta))
        yyyy_mm_dd=$(date --date="@$epoch" +"%Y/%m/%d")
        trace "checking $hostfile_dir/$yyyy_mm_dd/prolog_hostfile.$id.*"
        for host_file in $hostfile_dir/$yyyy_mm_dd/prolog_hostfile.$id.*; do
            if [ -e "$host_file" ]; then
                echo $host_file
                return
            fi
        done
    done
}

job_host_file=$(get_host_file $job_id $job_begin)
if [ -z "$job_host_file" ]; then
    fatal "$prog: cannot find host file for job '$job_id'"
fi
trace "job_host_file '$job_host_file'"

echo queue_name ${job_info[0]}
echo owner ${job_info[3]}
echo name ${job_info[4]}
echo id ${job_info[5]}
echo account ${job_info[6]}
echo submission_time ${job_info[8]}
echo start_time ${job_info[9]}
echo end_time ${job_info[10]}
echo failed ${job_info[11]}
echo exit_status ${job_info[12]}
echo granted_pe ${job_info[33]}
echo slots ${job_info[34]}
echo hosts $(cat $job_host_file)
echo
