# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20151002_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='LLiteOpenClose',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='MDCReqs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='MDCWait',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='OSCReqs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='OSCWait',
            field=models.FloatField(null=True),
        ),
    ]
