# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_auto_20160201_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=128)),
                ('uid', models.IntegerField(null=True)),
                ('pid', models.IntegerField(null=True)),
                ('VmHWM', models.FloatField(null=True)),
                ('Threads', models.IntegerField(null=True)),
                ('Cpus_allowed_list', models.CharField(max_length=128)),
                ('Mems_allowed_list', models.CharField(max_length=128)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.Job')),
            ],
        ),
    ]
