# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_proc'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='LnetAveMsgs',
            field=models.FloatField(null=True),
        ),
    ]
