# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_job_lnetavemsgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='MCDRAMBW',
            field=models.FloatField(null=True),
        ),
    ]
