# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_job_mcdrambw'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='BlockAveBW',
            field=models.FloatField(null=True),
        ),
    ]
