# Generated by Django 2.0.7 on 2018-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_auto_20180921_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='avg_sf_evictions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_sf_evictions',
        ),
        migrations.AddField(
            model_name='job',
            name='avg_sf_evictrate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_sf_evictrate',
            field=models.FloatField(null=True),
        ),
    ]
