# Generated by Django 2.0.7 on 2018-10-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0013_auto_20180921_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avg_page_hitrate',
            field=models.FloatField(null=True),
        ),
    ]
