# Generated by Django 2.0.7 on 2019-03-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0015_job_avg_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='max_load15',
            field=models.FloatField(null=True),
        ),
    ]
