# Generated by Django 2.2.4 on 2020-01-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0016_job_max_load15'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avg_vector_width',
            field=models.FloatField(null=True),
        ),
    ]
