# Generated by Django 2.2.4 on 2020-01-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0017_job_avg_vector_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avg_flops_32b',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='avg_vector_width_32b',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vecpercent_32b',
            field=models.FloatField(null=True),
        ),
    ]
