# Generated by Django 2.2.4 on 2020-01-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0018_auto_20200107_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='avg_flops',
            new_name='avg_flops_64b',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='avg_vector_width',
            new_name='avg_vector_width_64b',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='vecpercent',
            new_name='vecpercent_64b',
        ),
    ]
