# Generated by Django 3.0.3 on 2020-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0019_auto_20200107_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avg_gpuutil',
            field=models.FloatField(null=True),
        ),
    ]
